services:
  website:
    container_name: madine-website
    build: .
    volumes:
      - dolibarr-custom:/var/www/html/htdocs/custom
      - dolibarr-documents:/var/www/html/documents
    networks:
      - traefik_default
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.entrypoints=web
      - traefik.http.routers.website.rule=Host(`madine.timesaving.fr`)
      - traefik.http.services.website.loadbalancer.server.port=80

networks:
  traefik_default:
    external: true

volumes:
  dolibarr-custom:
  dolibarr-documents:
